services:
  consul:
    image: hashicorp/consul:1.17
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"          # Consul UI / API
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks: [ appnet ]

  metadata:
    build:
      context: .
      dockerfile: metadata/Dockerfile
    command: ["/app","--host=0.0.0.0","--port=8081","--consul=consul:8500"]
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks: [ appnet ]

  restaurant:
    build:
      context: .
      dockerfile: restaurant/Dockerfile
    command: ["/app","--host=0.0.0.0","--port=8082","--consul=consul:8500"]
    depends_on:
      consul:
        condition: service_healthy
      metadata:
        condition: service_started
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks: [ appnet ]

  review:
    build:
      context: .
      dockerfile: review/Dockerfile
    command: ["/app","--host=0.0.0.0","--port=8083","--consul=consul:8500"]
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8083/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks: [ appnet ]

networks:
  appnet: {}