services:
  consul:
    image: hashicorp/consul:1.18
    command: ["agent", "-dev", "-client=0.0.0.0", "-ui"]
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - appnet

  metadata:
    build:
      context: .
      dockerfile: ./metadata/Dockerfile
    environment:
      PORT: "8081"
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: "metadata"
    depends_on:
      - consul
    ports:
      - "8081:8081"
    networks:
      - appnet

  restaurant:
    build:
      context: .
      dockerfile: ./restaurant/Dockerfile
    environment:
      PORT: "8082"
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: "restaurant"
    depends_on:
      - consul
      - metadata
    ports:
      - "8082:8082"
    networks:
      - appnet

  review:
    build:
      context: .
      dockerfile: ./review/Dockerfile
    environment:
      PORT: "8083"
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: "review"
    depends_on:
      - consul
    ports:
      - "8083:8083"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
